Repository cormas/cormas, pull requests merged in 2021-04, with the labels that each got.

#380 Iss new open window
  repository/BaselineOfCormas/BaselineOfCormas.class.st
  repository/Cormas-Core/CMAbstractModel.class.st
  repository/Cormas-Core/CMResourceLocator.class.st
  repository/Cormas-Core/Cormas.class.st
  repository/Cormas-Core/RPackage.extension.st
  repository/Cormas-Tests/CMAbstractModelTest.class.st
  repository/Cormas-Tests/CMBasicModelTest.class.st
  repository/Cormas-Tests/CMTestModel.class.st
  repository/Cormas-Tests/CormasOpenMoleTest.class.st
  repository/Cormas-Tests/CormasUITest.class.st
  repository/Cormas-UI-Tests/CMApplicationProjectTest.class.st
  repository/Cormas-UI-Tests/CMModelOpenerTest.class.st
  repository/Cormas-UI-Tests/CMOpenerTest.class.st
  repository/Cormas-UI-Tests/CMProjectManagerTest.class.st
  repository/Cormas-UI-Tests/CMProjectModelTest.class.st
  repository/Cormas-UI-Tests/CMProjectOpenerTest.class.st
  repository/Cormas-UI/CMApplicationPreferences.class.st
  repository/Cormas-UI/CMApplicationProject.class.st
  repository/Cormas-UI/CMExternalBrowser.class.st
  repository/Cormas-UI/CMGitHubMigrator.class.st
  repository/Cormas-UI/CMGridViewMorphicAdapter.class.st
  repository/Cormas-UI/CMModel2ProjectMigrator.class.st
  repository/Cormas-UI/CMModelOpener.class.st
  repository/Cormas-UI/CMObject.class.st
  repository/Cormas-UI/CMPreferences.class.st
  repository/Cormas-UI/CMProjectFile.class.st
  repository/Cormas-UI/CMProjectManager.class.st
  repository/Cormas-UI/CMProjectModel.class.st
  repository/Cormas-UI/CMProjectOpener.class.st
  repository/Cormas-UI/CMResourceOpener.class.st
  repository/Cormas-UI/CMSpMetaProjectPresenter.class.st
  repository/Cormas-UI/CMSpOpenProjectNotebookPresenter.class.st
  repository/Cormas-UI/CMSpOpenProjectPresenter.class.st
  repository/Cormas-UI/CMSpPManagedPresenter.class.st
  repository/Cormas-UI/CMSpReadOnlyFormBuilder.class.st
  repository/Cormas-UI/CMSpaceAnimationRecorder.class.st
  repository/Cormas-UI/CMSpecModelComments.class.st
  repository/Cormas-UI/CMSpecProjectWindow.class.st
  repository/Cormas-UI/CMTranslator.class.st
  repository/Cormas-UI/ComposablePresenter.extension.st
  repository/Cormas-UI/FileExists.extension.st
  repository/Cormas-UI/FileReference.extension.st
  repository/Cormas-UI/Model.extension.st
  repository/Cormas-UI/Morph.extension.st
  repository/Cormas-UI/RTElement.extension.st
  repository/Cormas-UI/SettingTreeBuilder.extension.st
  repository/Cormas-UI/SpPresenter.extension.st
  repository/Cormas-UI/ZipFileSystemDirectory.extension.st
Labels: UI, cleaning, enhancement

#383 Removed + and - from protocol names
  repository/Cormas-Core/CMAbstractModel.class.st
  repository/Cormas-Core/CMAgentComm.class.st
  repository/Cormas-Core/CMAgentCommLocation.class.st
  repository/Cormas-Core/CMAgentLocation.class.st
  repository/Cormas-Core/CMArcEntity.class.st
  repository/Cormas-Core/CMEntity.class.st
  repository/Cormas-Core/CMGroup.class.st
  repository/Cormas-Core/CMGroupComm.class.st
  repository/Cormas-Core/CMGroupCommLocation.class.st
  repository/Cormas-Core/CMGroupLocation.class.st
  repository/Cormas-Core/CMMsg.class.st
  repository/Cormas-Core/CMNetworkComponentEntity.class.st
  repository/Cormas-Core/CMNetworkEntity.class.st
  repository/Cormas-Core/CMNodeEntity.class.st
  repository/Cormas-Core/CMObjectLocation.class.st
  repository/Cormas-Core/CMPassiveObject.class.st
  repository/Cormas-Core/CMSpaceModel.class.st
  repository/Cormas-Core/CMSpatialEntity.class.st
  repository/Cormas-Core/CMSpatialEntityAggregate.class.st
  repository/Cormas-Core/CMSpatialEntityCell.class.st
  repository/Cormas-Core/CMSpatialEntityElement.class.st
  repository/Cormas-Core/CMSpatialEntityNotConnex.class.st
  repository/Cormas-Core/CMSpatialEntitySet.class.st
  repository/Cormas-Core/Cormas.class.st
  repository/Cormas-Core/DataSaver_Asci.class.st
  repository/Cormas-Model-Conway/CMConwayCell.class.st
  repository/Cormas-Model-DemoAggregates/CMDemoAggregatesModel.class.st
  repository/Cormas-Model-DemoAggregates/CMDemoAggregatesPlot.class.st
  repository/Cormas-Model-Diffuse/CMDiffuseCell.class.st
  repository/Cormas-Model-Diffuse/CMDiffuseModel.class.st
  repository/Cormas-Model-ECEC/CMECECForager.class.st
  repository/Cormas-Model-ECEC/CMECECModel.class.st
  repository/Cormas-Model-ECEC/CMECECRestrained.class.st
  repository/Cormas-Model-ECEC/CMECECUnrestrained.class.st
  repository/Cormas-Model-ECEC/CMECECVegetationUnit.class.st
  repository/Cormas-Model-FireAutomata/CMFireAutomataFireman.class.st
  repository/Cormas-Model-PlotsRental/CMPRCell.class.st
  repository/Cormas-Model-PlotsRental/CMPRFarmer.class.st
  repository/Cormas-Model-ReHab/CMReHabFamily.class.st
  repository/Cormas-Model-ReHab/CMReHabModel.class.st
  repository/Cormas-Model-ReHab/CMReHabParkManager.class.st
  repository/Cormas-Model-ReHab/CMReHabPlantHarvester.class.st
  repository/Cormas-Model-ReHab/CMReHabStrategy.class.st
  repository/Cormas-Model-ReHab/CMReHabZone.class.st
Labels: cleaning

#382 Add #migrateProjects to simplify model to project migration
  repository/Cormas-UI/CMApplicationProject.class.st
  repository/Cormas-UI/CMModel2ProjectMigrator.class.st
Labels: enhancement

#387 Add trait for formattedWindowTitle: and make windows use this method …
  repository/Cormas-UI/CMSpecConfirmBeforeLaunch.class.st
  repository/Cormas-UI/CMSpecEditAttributes.class.st
  repository/Cormas-UI/CMSpecEntitiesBrowser.class.st
  repository/Cormas-UI/CMSpecInitialValueChooser.class.st
  repository/Cormas-UI/CMSpecModelComments.class.st
  repository/Cormas-UI/CMSpecObject.class.st
  repository/Cormas-UI/CMSpecProjectWindow.class.st
  repository/Cormas-UI/CMTranslator.class.st
  repository/Cormas-UI/ClyBrowserMorph.extension.st
  repository/Cormas-UI/PFStandardProjectWindow.extension.st
  repository/Cormas-UI/TCMUIUtils.trait.st
Labels: UI, enhancement

#393 Implements save projects on closing from the UI in #querySaveProject
  repository/Cormas-Core/CMResourceLocator.class.st
  repository/Cormas-UI/CMApplicationProject.class.st
  repository/Cormas-UI/CMModel2ProjectMigrator.class.st
  repository/Cormas-UI/CMProjectManager.class.st
  repository/Cormas-UI/CMProjectModel.class.st
  repository/Cormas-UI/CMProjectOpener.class.st
  repository/Cormas-UI/FileReference.extension.st
Labels: UI, enhancement, porting

#396 Issue395
  repository/Cormas-Core/CMAbstractModel.class.st
  repository/Cormas-Core/CMAgentLocation.class.st
  repository/Cormas-Core/CMCellsLoader.class.st
  repository/Cormas-Core/CMEntity.class.st
  repository/Cormas-Core/CMEnv2CellsConverter.class.st
  repository/Cormas-Core/CMResourceLocator.class.st
  repository/Cormas-Core/CMSpaceModel.class.st
  repository/Cormas-Core/CMSpatialEntity.class.st
  repository/Cormas-Core/CMSpatialEntityAggregate.class.st
  repository/Cormas-Core/CMSpatialEntitySet.class.st
  repository/Cormas-Model-Conway/CMConwayCell.class.st
  repository/Cormas-Model-Conway/CMConwayModel.class.st
  repository/Cormas-Model-Conway/CMConwayModelTest.class.st
  repository/Cormas-Model-DemoAggregates/CMDemoAggregatesFragmentedForest.class.st
  repository/Cormas-Model-DemoAggregates/CMDemoAggregatesGrove.class.st
  repository/Cormas-Model-DemoAggregates/CMDemoAggregatesModel.class.st
  repository/Cormas-Model-DemoAggregates/CMDemoAggregatesPlot.class.st
  repository/Cormas-Model-Diffuse/CMDiffuseAnt.class.st
  repository/Cormas-Model-Diffuse/CMDiffuseCell.class.st
  repository/Cormas-Model-Diffuse/CMDiffuseModel.class.st
  repository/Cormas-Model-ECEC/CMECECForager.class.st
  repository/Cormas-Model-ECEC/CMECECModel.class.st
  repository/Cormas-Model-ECEC/CMECECModelTest.class.st
  repository/Cormas-Model-ECEC/CMECECRestrained.class.st
  repository/Cormas-Model-ECEC/CMECECUnrestrained.class.st
  repository/Cormas-Model-ECEC/CMECECVegetationUnit.class.st
  repository/Cormas-Model-FireAutomata/CMFireAutomataModel.class.st
  repository/Cormas-Model-FireAutomata/CMFireAutomataModelTest.class.st
  repository/Cormas-Model-PlotsRental/CMPRFarmerTest.class.st
  repository/Cormas-Tests/CMAbstractModelTest.class.st
  repository/Cormas-Tests/CMTestModel.class.st
  repository/Cormas-Tests/CormasOpenMoleTest.class.st
  repository/Cormas-UI/CMSpecConfirmBeforeLaunch.class.st
Labels: bug, cleaning, pull requested

#397 Remove checkEntity:respondsTo: method, fix senders
  repository/Cormas-Core/CMAbstractModel.class.st
Labels: cleaning, priority 3

#398 Iss 366
  repository/Cormas-Core/CMAbstractModel.class.st
Labels: cleaning, priority 3

#399 PR for "No name of the model when creating new entities"
  repository/BaselineOfCormas/BaselineOfCormas.class.st
  repository/Cormas-Core/CMAbstractModel.class.st
  repository/Cormas-Core/String.extension.st
  repository/Cormas-Tests/StringTest.extension.st
  repository/Cormas-UI/CMProjectManager.class.st
  repository/Cormas-UI/CMProjectModel.class.st
  repository/Cormas-UI/CMProjectOpener.class.st
  repository/Cormas-UI/CMResourceOpener.class.st
  repository/Cormas-UI/CMSpecEntityAddInterface.class.st
Labels: enhancement, pull requested
